apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: b63e-tasks
  name: b63e-tasks
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.0-0
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/b63e-tasks-dev/b63e-tasks:0.0-0
    importPolicy: {}
    referencePolicy:
      type: Source
